#define ENUMERATIONS_CPP
#include "gl_wrappers/enumerations.h"

namespace fribr
{

#define OPENCV_FORMAT(FRIBR, OPENCV, GL_INT_FORMAT, GL_FORMAT, GL_READ_FORMAT, GL_TYPE) OPENCV
#define OPENGL_INTERNAL_FORMAT(FRIBR, OPENCV, GL_INT_FORMAT, GL_FORMAT, GL_READ_FORMAT, GL_TYPE) GL_INT_FORMAT
#define OPENGL_FORMAT(FRIBR, OPENCV, GL_INT_FORMAT, GL_FORMAT, GL_READ_FORMAT, GL_TYPE) GL_FORMAT
#define OPENGL_READ_FORMAT(FRIBR, OPENCV, GL_INT_FORMAT, GL_FORMAT, GL_READ_FORMAT, GL_TYPE) GL_READ_FORMAT
#define OPENGL_TYPE(FRIBR, OPENCV, GL_INT_FORMAT, GL_FORMAT, GL_READ_FORMAT, GL_TYPE) GL_TYPE

int TextureFormat::to_opengl_internal_format[] = { TEXTURE_FORMAT_LIST(OPENGL_INTERNAL_FORMAT) };
int TextureFormat::to_opengl_format[]          = { TEXTURE_FORMAT_LIST(OPENGL_FORMAT) };
int TextureFormat::to_opengl_read_format[]     = { TEXTURE_FORMAT_LIST(OPENGL_READ_FORMAT) };
int TextureFormat::to_opengl_type[]            = { TEXTURE_FORMAT_LIST(OPENGL_TYPE) };
int TextureFormat::to_opencv_type[]            = { TEXTURE_FORMAT_LIST(OPENCV_FORMAT) };

#undef OPENCV_FORMAT
#undef OPENGL_INTERNAL_FORMAT
#undef OPENGL_FORMAT
#undef OPENGL_READ_FORMAT
#undef OPENGL_TYPE

}
